In [1]:
import numpy as np
import pandas as pd
import sqlite3
import os

In [2]:
!pwd

/home/adam/Dokumenty/Data Science/Kodolamacz/data_science_bootcamp/Week4

In [3]:
import os

In [4]:
os.getcwd()

'/home/adam/Dokumenty/Data Science/Kodolamacz/data_science_bootcamp/Week4'

In [5]:
airlines = pd.read_csv("nycflights13_airlines.csv.gz", compression="gzip", comment="#")
airports = pd.read_csv("nycflights13_airports.csv.gz", compression="gzip", comment="#")
flights = pd.read_csv("nycflights13_flights.csv.gz", compression="gzip", comment="#")
planes = pd.read_csv("nycflights13_planes.csv.gz", compression="gzip", comment="#")
weather = pd.read_csv("nycflights13_weather.csv.gz", compression="gzip", comment="#")

In [6]:
airlines = pd.read_csv("nycflights13_airlines.csv.gz", comment="#")

In [7]:
airlines.head()

  carrier                    name
0      9E       Endeavor Air Inc.
1      AA  American Airlines Inc.
2      AS    Alaska Airlines Inc.
3      B6         JetBlue Airways
4      DL    Delta Air Lines Inc.

In [8]:
airports.head()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York

In [9]:
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00

In [10]:
planes.head()

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan

In [11]:
weather.head()

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,0,37.04,21.92,53.97,230.0,10.35702,11.918651,0.0,1013.9,10.0,2013-01-01 01:00:00
1,EWR,2013,1,1,1,37.04,21.92,53.97,230.0,13.80936,15.891535,0.0,1013.0,10.0,2013-01-01 02:00:00
2,EWR,2013,1,1,2,37.94,21.92,52.09,230.0,12.65858,14.567241,0.0,1012.6,10.0,2013-01-01 03:00:00
3,EWR,2013,1,1,3,37.94,23.00,54.51,230.0,13.80936,15.891535,0.0,1012.7,10.0,2013-01-01 04:00:00
4,EWR,2013,1,1,4,37.94,24.08,57.04,240.0,14.96014,17.215830,0.0,1012.8,10.0,2013-01-01 05:00:00

In [12]:
# pd.read_csv("/home/kodolamacz/bootcamp-2018-07/Pandas/nycflights13_airlines.csv.gz", )
# pd.read_csv("/home/kodolamacz/Pobrane/nycflights13_airlines.csv.gz",)

In [13]:
os.getcwd()

'/home/adam/Dokumenty/Data Science/Kodolamacz/data_science_bootcamp/Week4'

In [14]:
os.path.join("folder1", "folder2")

'folder1/folder2'

In [15]:
db_name = 'nycflights13.db'
os.path.join(os.getcwd(), db_name)

'/home/adam/Dokumenty/Data Science/Kodolamacz/data_science_bootcamp/Week4/nycflights13.db'

In [16]:
db_name = 'nycflights13.db'
os.remove(os.path.join(os.getcwd(), db_name))

FileNotFoundError: [Errno 2] No such file or directory: '/home/adam/Dokumenty/Data Science/Kodolamacz/data_science_bootcamp/Week4/nycflights13.db'

In [17]:
db_name = 'nycflights13.db'
con = sqlite3.connect(os.path.join(os.getcwd(), db_name))

planes.to_sql("planes", con, if_exists="replace")
airlines.to_sql("airlines", con, if_exists="replace")
flights.to_sql("flights", con, if_exists="replace")
airports.to_sql("airports", con, if_exists="replace")
weather.to_sql("weather", con, if_exists="replace")

# Przykładowe zapytania

In [18]:
# wszystko jak leci
sql_result = pd.read_sql_query("SELECT * FROM planes", con)
sql_result.head()

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan

In [19]:
# wszystkie wiersze, ale tylko 2 kolumny
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes", con)
sql_result.head()

  tailnum    year
0  N10156  2004.0
1  N102UW  1998.0
2  N103US  1999.0
3  N104UW  1999.0
4  N10575  2002.0

In [ ]:
# niektore wiersze, ale tylko 2 kolumny
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes WHERE year >= 2000", con)
sql_result

In [ ]:
# niektore wiersze, ale tylko 2 kolumny, laczenie warunkow
sql_result = pd.read_sql_query("SELECT * FROM planes WHERE year >= 2000 and seats > 100", con)
sql_result

In [ ]:
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes WHERE year == 2000 or year==2001", con)
sql_result

# 1

In [23]:
sql_result = pd.read_sql_query("SELECT DISTINCT engine FROM planes", con)
sql_result

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

In [27]:
wynik = pd.DataFrame(pd.unique(planes["engine"]))
wynik = wynik.rename({0: "engine"}, axis=1)
wynik

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

In [25]:
planes.engine.unique()

array(['Turbo-fan', 'Turbo-jet', 'Reciprocating', '4 Cycle',
       'Turbo-shaft', 'Turbo-prop'], dtype=object)

In [26]:
wynik = pd.DataFrame({"engine" : planes.engine.unique()})
# wynik.columns = ["engine"]
wynik

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

# 2

In [30]:
query = 'SELECT DISTINCT type, manufacturer, model, seats, engine FROM planes'
sql_result = pd.read_sql_query(query, con)
sql_result.head()

                      type      manufacturer      model  seats     engine
0  Fixed wing multi engine           EMBRAER  EMB-145XR     55  Turbo-fan
1  Fixed wing multi engine  AIRBUS INDUSTRIE   A320-214    182  Turbo-fan
2  Fixed wing multi engine           EMBRAER  EMB-145LR     55  Turbo-fan
3  Fixed wing multi engine            BOEING    737-824    149  Turbo-fan
4  Fixed wing multi engine            BOEING    767-332    330  Turbo-fan

In [54]:
resutl = planes[["type", "manufacturer", "model", "seats", "engine"]].drop_duplicates()
result.shape, sql_result.shape

((149, 5), (149, 5))

# 3

In [57]:
query = "SELECT COUNT(*), engine FROM planes GROUP BY engine"
sql_result = pd.read_sql_query(query, con)
sql_result.head()

   COUNT(*)         engine
0         2        4 Cycle
1        28  Reciprocating
2      2750      Turbo-fan
3       535      Turbo-jet
4         2     Turbo-prop

## tabela kontyngencji

In [87]:
result = pd.DataFrame(planes.engine.value_counts())
result = result.reset_index().sort_values(by="index")[["engine", "index"]].reset_index(drop=True)
# result.columns = ["COUNT(*)", "engine"]
result = result.rename({"engine": "COUNT(*)", "index": "engine"}, axis=1)
result

   COUNT(*)         engine
0         2        4 Cycle
1        28  Reciprocating
2      2750      Turbo-fan
3       535      Turbo-jet
4         2     Turbo-prop
5         5    Turbo-shaft

## group by

In [89]:
planes.groupby("engine", as_index=False).count() # zlicza nie puste wiersze

,engine,tailnum,year,type,manufacturer,model,engines,seats,speed
0,4 Cycle,2,1,2,2,2,2,2,1
1,Reciprocating,28,21,28,28,28,28,28,12
2,Turbo-fan,2750,2697,2750,2750,2750,2750,2750,0
3,Turbo-jet,535,526,535,535,535,535,535,8
4,Turbo-prop,2,2,2,2,2,2,2,1
5,Turbo-shaft,5,5,5,5,5,5,5,1

In [91]:
result2 = planes.groupby("engine", as_index=False).size()

In [96]:
result2.reset_index(drop=False).rename({0: "COUNT(*)"}, axis=1)[["COUNT(*)", "engine"]]

   COUNT(*)         engine
0         2        4 Cycle
1        28  Reciprocating
2      2750      Turbo-fan
3       535      Turbo-jet
4         2     Turbo-prop
5         5    Turbo-shaft

## Tabela przestawna

In [99]:
pd.pivot_table(planes[["engine"]], index=['engine'], aggfunc='size').reset_index()

          engine     0
0        4 Cycle     2
1  Reciprocating    28
2      Turbo-fan  2750
3      Turbo-jet   535
4     Turbo-prop     2
5    Turbo-shaft     5

## 4

In [102]:
query = "SELECT COUNT(*), engine, type FROM planes GROUP BY engine, type"
sql_result = pd.read_sql_query(query, con)
sql_result

   COUNT(*)         engine                      type
0         2        4 Cycle  Fixed wing single engine
1         5  Reciprocating   Fixed wing multi engine
2        23  Reciprocating  Fixed wing single engine
3      2750      Turbo-fan   Fixed wing multi engine
4       535      Turbo-jet   Fixed wing multi engine
5         2     Turbo-prop   Fixed wing multi engine
6         5    Turbo-shaft                Rotorcraft

## Tabela przestawna

In [104]:
result = pd.pivot_table(planes[["engine", "type"]], index=['engine', 'type'], aggfunc='size').reset_index()\
    [[0, "engine", "type"]]
result.columns = ["COUNT(*)", "engine", "type"]
result

   COUNT(*)         engine                      type
0         2        4 Cycle  Fixed wing single engine
1         5  Reciprocating   Fixed wing multi engine
2        23  Reciprocating  Fixed wing single engine
3      2750      Turbo-fan   Fixed wing multi engine
4       535      Turbo-jet   Fixed wing multi engine
5         2     Turbo-prop   Fixed wing multi engine
6         5    Turbo-shaft                Rotorcraft

## Group by

In [124]:
result2 = pd.DataFrame(planes[["engine", "type"]].groupby(["engine", "type"], as_index=False).size())
result2.reset_index(drop=False).rename({0: "COUNT(*)"}, axis=1)[["COUNT(*)", "engine", "type"]]

   COUNT(*)         engine                      type
0         2        4 Cycle  Fixed wing single engine
1         5  Reciprocating   Fixed wing multi engine
2        23  Reciprocating  Fixed wing single engine
3      2750      Turbo-fan   Fixed wing multi engine
4       535      Turbo-jet   Fixed wing multi engine
5         2     Turbo-prop   Fixed wing multi engine
6         5    Turbo-shaft                Rotorcraft

In [163]:
result3 = pd.crosstab(planes.engine, planes.type).reset_index()
result3 = result3.melt(id_vars=["engine"])
result3 =result3[result3.value > 0][["value", "engine", "type"]]
result3.columns = ["COUNT(*)", 'engine', 'type']
result3.sort_values(by="engine")

    COUNT(*)         engine                      type
6          2        4 Cycle  Fixed wing single engine
1          5  Reciprocating   Fixed wing multi engine
7         23  Reciprocating  Fixed wing single engine
2       2750      Turbo-fan   Fixed wing multi engine
3        535      Turbo-jet   Fixed wing multi engine
4          2     Turbo-prop   Fixed wing multi engine
17         5    Turbo-shaft                Rotorcraft

## 5

In [164]:
query = "SELECT MIN(year), AVG(year), MAX(year), engine, manufacturer \
        FROM planes GROUP BY engine, manufacturer"
sql_result = pd.read_sql_query(query, con)
sql_result

,MIN(year),AVG(year),MAX(year),engine,manufacturer
0,1975.0,1975.000000,1975.0,4 Cycle,CESSNA
1,NaN,NaN,NaN,4 Cycle,JOHN G HESS
2,NaN,NaN,NaN,Reciprocating,AMERICAN AIRCRAFT INC
3,2007.0,2007.000000,2007.0,Reciprocating,AVIAT AIRCRAFT INC
4,NaN,NaN,NaN,Reciprocating,BARKER JACK L
5,1959.0,1971.142857,1983.0,Reciprocating,CESSNA
6,2007.0,2007.000000,2007.0,Reciprocating,CIRRUS DESIGN CORP
7,1959.0,1959.000000,1959.0,Reciprocating,DEHAVILLAND
8,1956.0,1956.000000,1956.0,Reciprocating,DOUGLAS
9,2007.0,2007.000000,2007.0,Reciprocating,FRIEDEMANN JON
10,NaN,NaN,NaN,Reciprocating,HURLEY JAMES LARRY
11,1985.0,1985.000000,1985.0,Reciprocating,KILDALL GARY
12,NaN,NaN,NaN,Reciprocating,LAMBERT RICHARD
13,1985.0,1985.000000,1985.0,Reciprocating,LEBLANC GLENN T
14,1993.0,1993.000000,1993.0,Reciprocating,MARZ BARRY
15,NaN,NaN,NaN,Reciprocating,PAIR MIKE E
16,1968.0,1976.400000,1980.0,Reciprocating,PIPER
17,1985.0,1985.000000,1985.0,Reciprocating,STEWART MACO
18,2002.0,2007.281734,2013.0,Turbo-fan,AIRBUS
19,1992.0,1998.599251,2013.0,Turbo-fan,AIRBUS INDUSTRIE
20,1986.0,1986.000000,1986.0,Turbo-fan,AVIONS MARCEL DASSAULT
21,1965.0,2001.210400,2013.0,Turbo-fan,BOEING
22,1998.0,2004.486188,2013.0,Turbo-fan,BOMBARDIER INC
23,1997.0,1997.333333,1998.0,Turbo-fan,CANADAIR
24,1979.0,1979.000000,1979.0,Turbo-fan,CESSNA
25,1998.0,2003.613014,2013.0,Turbo-fan,EMBRAER
26,1992.0,1992.000000,1992.0,Turbo-fan,GULFSTREAM AEROSPACE
27,NaN,NaN,NaN,Turbo-fan,LEARJET INC
28,1986.0,1989.704545,1997.0,Turbo-fan,MCDONNELL DOUGLAS
29,1987.0,1989.737864,1993.0,Turbo-fan,MCDONNELL DOUGLAS AIRCRAFT CO
30,2002.0,2002.000000,2002.0,Turbo-jet,AIRBUS
31,1989.0,1997.439024,2004.0,Turbo-jet,AIRBUS INDUSTRIE
32,1984.0,1996.368272,2005.0,Turbo-jet,BOEING
33,1974.0,1974.000000,1974.0,Turbo-jet,CANADAIR LTD
34,1999.0,1999.000000,1999.0,Turbo-jet,EMBRAER
35,1976.0,1976.000000,1976.0,Turbo-jet,GULFSTREAM AEROSPACE
36,1975.0,1990.714286,1998.0,Turbo-jet,MCDONNELL DOUGLAS
37,1991.0,1991.928571,1992.0,Turbo-jet,MCDONNELL DOUGLAS CORPORATION
38,1967.0,1969.500000,1972.0,Turbo-prop,BEECH
39,2001.0,2001.000000,2001.0,Turbo-shaft,AGUSTA SPA
40,1975.0,1984.500000,1994.0,Turbo-shaft,BELL
41,2012.0,2012.000000,2012.0,Turbo-shaft,ROBINSON HELICOPTER CO
42,1985.0,1985.000000,1985.0,Turbo-shaft,SIKORSKY

## group by

In [226]:
result = planes.groupby(['engine', 'manufacturer'], as_index=False).agg({"year": ["min", "mean", "max"]})

In [227]:
result[[("engine", ""), ("manufacturer", ""), ("year", "min"), ("year", "mean"), ("year", "max")]]

           engine                   manufacturer    year
                                                     min         mean     max
0         4 Cycle                         CESSNA  1975.0  1975.000000  1975.0
1         4 Cycle                    JOHN G HESS     NaN          NaN     NaN
2   Reciprocating          AMERICAN AIRCRAFT INC     NaN          NaN     NaN
3   Reciprocating             AVIAT AIRCRAFT INC  2007.0  2007.000000  2007.0
4   Reciprocating                  BARKER JACK L     NaN          NaN     NaN
5   Reciprocating                         CESSNA  1959.0  1971.142857  1983.0
6   Reciprocating             CIRRUS DESIGN CORP  2007.0  2007.000000  2007.0
7   Reciprocating                    DEHAVILLAND  1959.0  1959.000000  1959.0
8   Reciprocating                        DOUGLAS  1956.0  1956.000000  1956.0
9   Reciprocating                 FRIEDEMANN JON  2007.0  2007.000000  2007.0
10  Reciprocating             HURLEY JAMES LARRY     NaN          NaN     NaN
11  Reciprocating                   KILDALL GARY  1985.0  1985.000000  1985.0
12  Reciprocating                LAMBERT RICHARD     NaN          NaN     NaN
13  Reciprocating                LEBLANC GLENN T  1985.0  1985.000000  1985.0
14  Reciprocating                     MARZ BARRY  1993.0  1993.000000  1993.0
15  Reciprocating                    PAIR MIKE E     NaN          NaN     NaN
16  Reciprocating                          PIPER  1968.0  1976.400000  1980.0
17  Reciprocating                   STEWART MACO  1985.0  1985.000000  1985.0
18      Turbo-fan                         AIRBUS  2002.0  2007.281734  2013.0
19      Turbo-fan               AIRBUS INDUSTRIE  1992.0  1998.599251  2013.0
20      Turbo-fan         AVIONS MARCEL DASSAULT  1986.0  1986.000000  1986.0
21      Turbo-fan                         BOEING  1965.0  2001.210400  2013.0
22      Turbo-fan                 BOMBARDIER INC  1998.0  2004.486188  2013.0
23      Turbo-fan                       CANADAIR  1997.0  1997.333333  1998.0
24      Turbo-fan                         CESSNA  1979.0  1979.000000  1979.0
25      Turbo-fan                        EMBRAER  1998.0  2003.613014  2013.0
26      Turbo-fan           GULFSTREAM AEROSPACE  1992.0  1992.000000  1992.0
27      Turbo-fan                    LEARJET INC     NaN          NaN     NaN
28      Turbo-fan              MCDONNELL DOUGLAS  1986.0  1989.704545  1997.0
29      Turbo-fan  MCDONNELL DOUGLAS AIRCRAFT CO  1987.0  1989.737864  1993.0
30      Turbo-jet                         AIRBUS  2002.0  2002.000000  2002.0
31      Turbo-jet               AIRBUS INDUSTRIE  1989.0  1997.439024  2004.0
32      Turbo-jet                         BOEING  1984.0  1996.368272  2005.0
33      Turbo-jet                   CANADAIR LTD  1974.0  1974.000000  1974.0
34      Turbo-jet                        EMBRAER  1999.0  1999.000000  1999.0
35      Turbo-jet           GULFSTREAM AEROSPACE  1976.0  1976.000000  1976.0
36      Turbo-jet              MCDONNELL DOUGLAS  1975.0  1990.714286  1998.0
37      Turbo-jet  MCDONNELL DOUGLAS CORPORATION  1991.0  1991.928571  1992.0
38     Turbo-prop                          BEECH  1967.0  1969.500000  1972.0
39    Turbo-shaft                     AGUSTA SPA  2001.0  2001.000000  2001.0
40    Turbo-shaft                           BELL  1975.0  1984.500000  1994.0
41    Turbo-shaft         ROBINSON HELICOPTER CO  2012.0  2012.000000  2012.0
42    Turbo-shaft                       SIKORSKY  1985.0  1985.000000  1985.0

## 6

In [210]:
query = "SELECT * FROM planes WHERE speed IS NOT NULL"
sql_result = pd.read_sql_query(query, con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,424,N201AA,1959.0,Fixed wing single engine,CESSNA,150,1,2,90.0,Reciprocating
1,427,N202AA,1980.0,Fixed wing multi engine,CESSNA,421C,2,8,90.0,Reciprocating
2,821,N350AA,1980.0,Fixed wing multi engine,PIPER,PA-31-350,2,8,162.0,Reciprocating
3,893,N364AA,1973.0,Fixed wing multi engine,CESSNA,310Q,2,6,167.0,Reciprocating
4,1027,N378AA,1963.0,Fixed wing single engine,CESSNA,172E,1,4,105.0,Reciprocating
5,1037,N381AA,1956.0,Fixed wing multi engine,DOUGLAS,DC-7BF,4,102,232.0,Reciprocating
6,1190,N425AA,1968.0,Fixed wing single engine,PIPER,PA-28-180,1,4,107.0,Reciprocating
7,1430,N508AA,1975.0,Rotorcraft,BELL,206B,1,5,112.0,Turbo-shaft
8,1480,N519MQ,1983.0,Fixed wing single engine,CESSNA,A185F,1,6,127.0,Reciprocating
9,1515,N525AA,1980.0,Fixed wing multi engine,PIPER,PA-31-350,2,8,162.0,Reciprocating
10,1589,N545AA,1976.0,Fixed wing single engine,PIPER,PA-32R-300,1,7,126.0,Reciprocating
11,1694,N567AA,1959.0,Fixed wing single engine,DEHAVILLAND,OTTER DHC-3,1,16,95.0,Reciprocating
12,1813,N600TR,1979.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
13,1867,N615AA,1967.0,Fixed wing multi engine,BEECH,65-A90,2,9,202.0,Turbo-prop
14,1883,N621AA,1975.0,Fixed wing single engine,CESSNA,172M,1,4,108.0,4 Cycle
15,2131,N675MC,1975.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
16,2309,N737MQ,1977.0,Fixed wing single engine,CESSNA,172N,1,4,105.0,Reciprocating
17,2402,N762NC,1976.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
18,2432,N767NC,1977.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
19,2472,N774NC,1978.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
20,2483,N777NC,1979.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
21,2492,N779NC,1979.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet
22,2503,N782NC,1980.0,Fixed wing multi engine,MCDONNELL DOUGLAS,DC-9-51,2,139,432.0,Turbo-jet

In [221]:
result = planes.dropna(subset=["speed"])
result.shape

(23, 9)

## 7

In [228]:
query = "SELECT tailnum FROM planes WHERE year >= 2010"
sql_result = pd.read_sql_query(query, con)
sql_result

    tailnum
0    N127UW
1    N128UW
2    N150UW
3    N151UW
4    N152UW
5    N153UW
6    N154UW
7    N155UW
8    N156UW
9    N157UW
10   N198UW
11   N199UW
12   N205FR
13   N206FR
14   N207FR
15   N208FR
16   N20904
17   N209FR
18   N210FR
19   N211FR
20   N213FR
21   N214FR
22   N216FR
23   N26906
24   N272PQ
25   N27477
26   N27901
27   N279PQ
28   N28457
29   N28478
..      ...
271  N913JB
272  N943WN
273  N944WN
274  N945WN
275  N946WN
276  N947WN
277  N948WN
278  N949WN
279  N950WN
280  N951WN
281  N952FR
282  N952WN
283  N953FR
284  N953WN
285  N954WN
286  N955WN
287  N956WN
288  N957WN
289  N958WN
290  N959WN
291  N960WN
292  N961WN
293  N962WN
294  N963WN
295  N964WN
296  N965WN
297  N966WN
298  N967WN
299  N968WN
300  N969WN

[301 rows x 1 columns]

In [235]:
planes[planes["year"] >= 2010][["tailnum"]].reset_index(drop=True)

    tailnum
0    N127UW
1    N128UW
2    N150UW
3    N151UW
4    N152UW
5    N153UW
6    N154UW
7    N155UW
8    N156UW
9    N157UW
10   N198UW
11   N199UW
12   N205FR
13   N206FR
14   N207FR
15   N208FR
16   N20904
17   N209FR
18   N210FR
19   N211FR
20   N213FR
21   N214FR
22   N216FR
23   N26906
24   N272PQ
25   N27477
26   N27901
27   N279PQ
28   N28457
29   N28478
..      ...
271  N913JB
272  N943WN
273  N944WN
274  N945WN
275  N946WN
276  N947WN
277  N948WN
278  N949WN
279  N950WN
280  N951WN
281  N952FR
282  N952WN
283  N953FR
284  N953WN
285  N954WN
286  N955WN
287  N956WN
288  N957WN
289  N958WN
290  N959WN
291  N960WN
292  N961WN
293  N962WN
294  N963WN
295  N964WN
296  N965WN
297  N966WN
298  N967WN
299  N968WN
300  N969WN

[301 rows x 1 columns]

## 8

In [236]:
query = "SELECT tailnum FROM planes WHERE seats BETWEEN 100 and 200 LIMIT 20"
sql_result = pd.read_sql_query(query, con)
sql_result

   tailnum
0   N102UW
1   N103US
2   N104UW
3   N105UW
4   N107US
5   N108UW
6   N109UW
7   N110UW
8   N111US
9   N11206
10  N112US
11  N113UW
12  N114UW
13  N117UW
14  N118US
15  N119US
16  N12109
17  N12114
18  N12116
19  N12125

In [244]:
planes[(planes["seats"] >= 100) & (planes["seats"] < 200)][["tailnum"]].head(20)

   tailnum
1   N102UW
2   N103US
3   N104UW
5   N105UW
6   N107US
7   N108UW
8   N109UW
9   N110UW
33  N111US
34  N11206
35  N112US
36  N113UW
37  N114UW
46  N117UW
47  N118US
48  N119US
51  N12109
52  N12114
53  N12116
55  N12125

In [ ]:
planes

## 9

In [262]:
query = 'SELECT * FROM planes WHERE manufacturer IN ("BOEING","AIRBUS", "EMBRAER")'
sql_result = pd.read_sql_query(query, con)
sql_result.shape

(2265, 10)

In [264]:
result = planes[planes["manufacturer"].isin(["BOEING","AIRBUS", "EMBRAER"])]
result

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
10,N11106,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
11,N11107,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
12,N11109,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
13,N11113,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
14,N11119,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
15,N11121,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
16,N11127,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
17,N11137,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
18,N11140,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
19,N11150,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
20,N11155,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
21,N11164,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
22,N11165,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
23,N11176,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
24,N11181,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
25,N11184,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
26,N11187,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
27,N11189,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
28,N11191,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
29,N11192,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
30,N11193,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
31,N11194,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
32,N11199,2006.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
34,N11206,2000.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
38,N11535,2001.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
39,N11536,2001.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
40,N11539,2001.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
41,N11544,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...
3259,N968AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3261,N968WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,NaN,Turbo-fan
3262,N969AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3264,N969WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,NaN,Turbo-fan
3265,N970AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3267,N971AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3269,N972AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3272,N974AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3274,N975AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3277,N977AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3279,N978AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3282,N979AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3284,N980AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3286,N981AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3288,N982AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3290,N983AT,NaN,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3293,N985AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3295,N986AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3297,N987AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3299,N988AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3301,N989AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3303,N990AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3305,N991AT,NaN,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3307,N992AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3309,N993AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3311,N994AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3313,N995AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3315,N996AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3317,N997AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3319,N998AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan

## 10

In [265]:
query = 'SELECT * FROM planes WHERE manufacturer IN ("BOEING","AIRBUS", "EMBRAER") AND seats>300'
sql_result = pd.read_sql_query(query, con)
sql_result.shape

(193, 10)

In [272]:
result = planes[(planes["manufacturer"].isin(["BOEING","AIRBUS", "EMBRAER"])) & (planes["seats"] > 300)]
result.shape

(193, 9)

## 11

In [280]:
query = 'SELECT manufacturer, COUNT(*) FROM planes WHERE seats > 200 GROUP BY manufacturer'
sql_result = pd.read_sql_query(query, con)
sql_result

       manufacturer  COUNT(*)
0            AIRBUS        66
1  AIRBUS INDUSTRIE         4
2            BOEING       225

In [297]:
result = planes[planes["seats"] > 200].groupby("manufacturer").size().reset_index().rename({0:"licznosc"}, axis=1)
result
#result = pd.DataFrame(result)
#result.shape

       manufacturer  licznosc
0            AIRBUS        66
1  AIRBUS INDUSTRIE         4
2            BOEING       225

## 12

In [298]:
query = 'SELECT manufacturer, COUNT(*) FROM planes GROUP BY manufacturer HAVING COUNT(*) > 10'
sql_result = pd.read_sql_query(query, con)
sql_result

                    manufacturer  COUNT(*)
0                         AIRBUS       336
1               AIRBUS INDUSTRIE       400
2                         BOEING      1630
3                 BOMBARDIER INC       368
4                        EMBRAER       299
5              MCDONNELL DOUGLAS       120
6  MCDONNELL DOUGLAS AIRCRAFT CO       103
7  MCDONNELL DOUGLAS CORPORATION        14

In [321]:
result = planes.groupby("manufacturer").size()

In [323]:
result[result > 10].reset_index()

                    manufacturer     0
0                         AIRBUS   336
1               AIRBUS INDUSTRIE   400
2                         BOEING  1630
3                 BOMBARDIER INC   368
4                        EMBRAER   299
5              MCDONNELL DOUGLAS   120
6  MCDONNELL DOUGLAS AIRCRAFT CO   103
7  MCDONNELL DOUGLAS CORPORATION    14

## 13

In [324]:
query = 'SELECT manufacturer, COUNT(*) FROM planes WHERE seats > 200 GROUP BY manufacturer HAVING COUNT(*) > 10'
sql_result = pd.read_sql_query(query, con)
sql_result

  manufacturer  COUNT(*)
0       AIRBUS        66
1       BOEING       225

In [326]:
result = planes[planes["seats"] > 200].groupby("manufacturer").size()
result[result > 10].reset_index()

  manufacturer    0
0       AIRBUS   66
1       BOEING  225

## 14

In [327]:
query = 'SELECT manufacturer, COUNT(*) AS howmany FROM planes GROUP BY manufacturer ORDER BY howmany'
sql_result = pd.read_sql_query(query, con)
sql_result

                     manufacturer  howmany
0                      AGUSTA SPA        1
1              AVIAT AIRCRAFT INC        1
2          AVIONS MARCEL DASSAULT        1
3                   BARKER JACK L        1
4                    CANADAIR LTD        1
5              CIRRUS DESIGN CORP        1
6                     DEHAVILLAND        1
7                         DOUGLAS        1
8                  FRIEDEMANN JON        1
9              HURLEY JAMES LARRY        1
10                    JOHN G HESS        1
11                   KILDALL GARY        1
12                LAMBERT RICHARD        1
13                    LEARJET INC        1
14                LEBLANC GLENN T        1
15                     MARZ BARRY        1
16                    PAIR MIKE E        1
17         ROBINSON HELICOPTER CO        1
18                       SIKORSKY        1
19          AMERICAN AIRCRAFT INC        2
20                          BEECH        2
21                           BELL        2
22           GULFSTREAM AEROSPACE        2
23                   STEWART MACO        2
24                          PIPER        5
25                       CANADAIR        9
26                         CESSNA        9
27  MCDONNELL DOUGLAS CORPORATION       14
28  MCDONNELL DOUGLAS AIRCRAFT CO      103
29              MCDONNELL DOUGLAS      120
30                        EMBRAER      299
31                         AIRBUS      336
32                 BOMBARDIER INC      368
33               AIRBUS INDUSTRIE      400
34                         BOEING     1630

In [340]:
planes.groupby("manufacturer").size().reset_index().rename({0: "howmany"}, axis=1).sort_values(by="howmany").reset_index(drop=True)

                     manufacturer  howmany
0                      AGUSTA SPA        1
1                         DOUGLAS        1
2                     DEHAVILLAND        1
3              CIRRUS DESIGN CORP        1
4              HURLEY JAMES LARRY        1
5                    CANADAIR LTD        1
6                     JOHN G HESS        1
7                    KILDALL GARY        1
8                        SIKORSKY        1
9                 LAMBERT RICHARD        1
10                LEBLANC GLENN T        1
11                  BARKER JACK L        1
12         AVIONS MARCEL DASSAULT        1
13             AVIAT AIRCRAFT INC        1
14                     MARZ BARRY        1
15                    PAIR MIKE E        1
16         ROBINSON HELICOPTER CO        1
17                    LEARJET INC        1
18                 FRIEDEMANN JON        1
19                   STEWART MACO        2
20                           BELL        2
21                          BEECH        2
22          AMERICAN AIRCRAFT INC        2
23           GULFSTREAM AEROSPACE        2
24                          PIPER        5
25                         CESSNA        9
26                       CANADAIR        9
27  MCDONNELL DOUGLAS CORPORATION       14
28  MCDONNELL DOUGLAS AIRCRAFT CO      103
29              MCDONNELL DOUGLAS      120
30                        EMBRAER      299
31                         AIRBUS      336
32                 BOMBARDIER INC      368
33               AIRBUS INDUSTRIE      400
34                         BOEING     1630

## 15

In [346]:
query = 'SELECT manufacturer, COUNT(*) AS howmany FROM planes GROUP BY manufacturer ORDER BY howmany DESC LIMIT 10'
sql_result = pd.read_sql_query(query, con)
sql_result

                    manufacturer  howmany
0                         BOEING     1630
1               AIRBUS INDUSTRIE      400
2                 BOMBARDIER INC      368
3                         AIRBUS      336
4                        EMBRAER      299
5              MCDONNELL DOUGLAS      120
6  MCDONNELL DOUGLAS AIRCRAFT CO      103
7  MCDONNELL DOUGLAS CORPORATION       14
8                       CANADAIR        9
9                         CESSNA        9

In [349]:
result = planes.groupby("manufacturer").size().reset_index().rename({0: "howmany"}, axis=1)
result.sort_values(by="howmany", ascending=False).reset_index(drop=True).head(10)

                    manufacturer  howmany
0                         BOEING     1630
1               AIRBUS INDUSTRIE      400
2                 BOMBARDIER INC      368
3                         AIRBUS      336
4                        EMBRAER      299
5              MCDONNELL DOUGLAS      120
6  MCDONNELL DOUGLAS AIRCRAFT CO      103
7  MCDONNELL DOUGLAS CORPORATION       14
8                         CESSNA        9
9                       CANADAIR        9

## 16

In [350]:
query = 'SELECT * FROM planes WHERE year >= 2012 ORDER BY year, seats'
sql_result = pd.read_sql_query(query, con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,None,Turbo-shaft
1,815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
2,825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
3,837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
4,2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
5,2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
6,2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
7,2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
8,2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
9,2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
10,2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
11,2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
12,2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
13,2644,N8312C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
14,2645,N8313F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
15,2646,N8314L,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
16,2647,N8315C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
17,2648,N8316H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
18,2649,N8317M,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
19,2650,N8318F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
20,2651,N8319F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
21,2656,N8320J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
22,2657,N8321D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
23,2658,N8322X,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
24,2659,N8323C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
25,2660,N8324A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
26,2661,N8325D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
27,2662,N8326F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
28,2663,N8327A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
29,2664,N8328A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
157,230,N156UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
158,233,N157UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
159,418,N198UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
160,421,N199UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
161,2618,N827JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,None,Turbo-fan
162,2623,N828JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,None,Turbo-fan
163,2675,N834JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,None,Turbo-fan
164,1147,N409AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
165,1160,N413AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
166,1173,N419AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
167,1184,N423AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
168,1207,N431AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
169,1214,N433AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
170,1223,N435AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
171,1241,N440AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
172,1248,N442AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
173,1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
174,1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
175,1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
176,1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
177,1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
178,1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
179,1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
180,1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
181,1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
182,1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
183,1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
184,2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
185,2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
186,2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan

In [351]:
planes[planes["year"] >= 2012].sort_values(["year", "seats"])

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,NaN,Turbo-shaft
815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2644,N8312C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2645,N8313F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2646,N8314L,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2647,N8315C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2648,N8316H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2649,N8317M,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2650,N8318F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2651,N8319F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2656,N8320J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2657,N8321D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2658,N8322X,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2659,N8323C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2660,N8324A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2661,N8325D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2662,N8326F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2663,N8327A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2664,N8328A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...
230,N156UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
233,N157UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
418,N198UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
421,N199UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
2618,N827JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,NaN,Turbo-fan
2623,N828JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,NaN,Turbo-fan
2675,N834JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,NaN,Turbo-fan
1147,N409AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1160,N413AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1173,N419AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1184,N423AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1207,N431AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1214,N433AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1223,N435AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1241,N440AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1248,N442AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan

## 17

In [352]:
query = 'SELECT * FROM planes WHERE year >= 2012 ORDER BY seats, year'
sql_result = pd.read_sql_query(query, con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,None,Turbo-shaft
1,815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
2,825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
3,837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
4,843,N354JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
5,848,N355JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
6,859,N358JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
7,908,N368JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
8,956,N373JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
9,989,N374JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
10,1003,N375JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
11,578,N272PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
12,600,N279PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
13,628,N292PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
14,630,N293PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
15,633,N294PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
16,636,N295PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
17,639,N296PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
18,642,N297PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
19,645,N298PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
20,650,N299PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
21,2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
22,2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
23,2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
24,2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
25,2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
26,2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
27,2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
28,2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
29,2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
157,1293,N45905,2012.0,Fixed wing multi engine,BOEING,787-8,2,260,None,Turbo-fan
158,1065,N385HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
159,1068,N386HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
160,1075,N388HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
161,1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
162,1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
163,1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
164,1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
165,1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
166,1637,N555AY,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
167,1646,N556UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
168,1652,N557UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
169,1657,N558UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
170,1662,N559UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
171,1666,N560UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
172,1670,N561UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
173,1674,N562UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
174,1678,N563UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
175,1683,N564UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
176,1688,N565UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
177,1693,N566UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
178,1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
179,1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
180,1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
181,1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
182,1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
183,1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
184,2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
185,2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
186,2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan

In [353]:
planes[planes["year"] >= 2012].sort_values(["seats", "year"])

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,NaN,Turbo-shaft
815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
843,N354JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
848,N355JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
859,N358JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
908,N368JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
956,N373JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
989,N374JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
1003,N375JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
578,N272PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
600,N279PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
628,N292PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
630,N293PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
633,N294PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
636,N295PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
639,N296PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
642,N297PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
645,N298PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
650,N299PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...
1293,N45905,2012.0,Fixed wing multi engine,BOEING,787-8,2,260,NaN,Turbo-fan
1065,N385HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1068,N386HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1075,N388HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1637,N555AY,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1646,N556UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1652,N557UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1657,N558UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1662,N559UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1666,N560UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1670,N561UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1674,N562UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1678,N563UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1683,N564UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1688,N565UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1693,N566UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan

## Wybierz 100 losowych wierszy z airports

In [357]:
airports.sample(100)

,faa,name,lat,lon,alt,tz,dst,tzone
890,MLI,Quad City Intl,41.448528,-90.507539,590,-6,A,America/Chicago
111,AIZ,Lee C Fine Memorial Airport,38.096035,-92.549487,869,-6,A,America/Chicago
755,KWT,Kwethluk Airport,60.790278,-161.443611,30,-9,A,America/Anchorage
582,HDN,Yampa Valley,40.481181,-107.217660,6602,-7,A,America/Denver
1360,UT3,Hite Airport,37.891655,-110.384029,3840,-7,A,America/Denver
23,23M,Clarke CO,32.051700,-88.443400,320,-6,A,America/Chicago
87,ABQ,Albuquerque International Sunport,35.040222,-106.609194,5355,-7,A,America/Denver
873,MHR,Sacramento Mather,38.553897,-121.297592,96,-8,A,America/Los_Angeles
926,MTH,Florida Keys Marathon Airport,24.726111,-81.051389,7,-5,A,America/New_York
1144,REI,Redlands Municipal Airport,34.085250,-117.146388,1574,-8,A,America/Los_Angeles
98,ADS,Addison,32.968559,-96.836448,644,-6,A,America/Chicago
988,NXX,Willow Grove Nas Jrb,40.199833,-75.148167,358,-5,A,America/New_York
968,NLC,Lemoore Nas,36.333012,-119.952080,234,-8,A,America/Los_Angeles
1348,TZR,Bolton Field,39.901111,-83.136944,905,-5,A,America/New_York
773,LBF,North Platte Regional Airport Lee Bird Field,41.126200,-100.684000,2776,-6,A,America/Chicago
1373,VDZ,Valdez Pioneer Fld,61.133949,-146.248342,118,-9,A,America/Anchorage
659,IMM,Immokalee,26.433889,-81.401389,37,-5,A,America/New_York
916,MRK,Marco Islands,25.995028,-81.672528,5,-5,A,America/New_York
459,EWN,Craven Co Rgnl,35.072972,-77.042944,18,-5,A,America/New_York
1136,RCE,Roche Harbor Seaplane Base,48.608056,-123.159722,0,-8,A,America/Los_Angeles
379,DOV,Dover Afb,39.129539,-75.465958,28,-5,A,America/New_York
756,KYK,Karuluk Airport,57.566944,-154.450278,137,-9,A,America/Anchorage
1427,X49,South Lakeland Airport,27.933358,-82.043974,110,-5,A,America/New_York
757,KYU,Koyukuk Airport,64.875833,-157.730556,149,-9,A,America/Anchorage
986,NUW,Whidbey Island Nas,48.351803,-122.655906,47,-8,A,America/Los_Angeles
441,ENV,Wendover,40.718694,-114.030889,4237,-7,A,America/Denver
908,MPB,Miami Seaplane Base,25.778300,-80.170300,0,-5,A,America/New_York
1364,UUU,Newport State,41.533056,-71.282222,172,-5,A,America/New_York
195,BIF,Biggs Aaf,31.849528,-106.380039,3948,-7,A,America/Denver
1322,TOA,Zamperini Field Airport,33.803392,-118.339611,101,-8,A,America/Los_Angeles
...,...,...,...,...,...,...,...,...
1242,SLQ,Sleetmute Airport,61.700566,-157.165833,190,-9,A,America/Anchorage
547,GNT,Grants Milan Muni,35.167286,-107.901989,6537,-7,A,America/Denver
1196,SBY,Salisbury Ocean City Wicomico Rgnl,38.340525,-75.510289,52,-5,A,America/New_York
46,49X,Chemehuevi Valley,34.528889,-114.431971,638,-8,A,America/Los_Angeles
885,MKL,Mc Kellar Sipes Rgnl,35.599889,-88.915611,434,-6,A,America/Chicago
424,EGX,Egegik Airport,58.185556,-157.375556,92,-9,A,America/Anchorage
463,F57,Seaplane Base,28.057500,-81.762806,140,-5,A,America/New_York
1297,TCC,Tucumcari Muni,35.182777,-103.603186,4065,-7,A,America/Denver
348,CZF,Cape Romanzof Lrrs,61.780297,-166.038747,457,-9,A,America/Anchorage
133,ANQ,Tri-State Steuben County Airport,41.639698,-85.083493,995,-5,A,America/New_York
1291,SYB,Seal Bay Seaplane Base,58.166667,-152.500000,0,-9,A,America/Anchorage
1270,STG,St. George Airport,56.577222,-169.663611,125,-9,A,America/Anchorage
257,CAE,Columbia Metropolitan,33.938833,-81.119528,236,-5,A,America/New_York
1107,PSM,Pease International Tradeport,43.077900,-70.823300,100,-5,A,America/New_York
573,GVT,Majors,33.067839,-96.065333,535,-6,A,America/Chicago
183,BFF,Western Nebraska Regional Airport,41.874000,-103.596000,3967,-7,A,America/Denver
725,KKH,Kongiganak Airport,59.960833,-162.881111,30,-9,A,America/Anchorage
1449,ZSF,Springfield Amtrak Station,42.106000,-72.593054,65,-5,A,America/New_York
1273,STL,Lambert St Louis Intl,38.748697,-90.370028,618,-6,A,America/Chicago
122,ALS,San Luis Valley Regional Airport,37.435000,-105.866667,7539,-7,A,America/Denver
350,CZN,Chisana Airport,62.071111,-142.048333,1011,-9,A,America/Anchorage
429,EKO,Elko Regional Airport,40.824900,-115.792000,5140,-8,A,America/Los_Angeles
387,DSM,Des Moines Intl,41.533972,-93.663083,958,-6,A,America/Chicago
656,ILI,Iliamna,59.754356,-154.910961,186,-9,A,America/Anchorage
188,BFT,Beaufort,32.477411,-80.723161,37,-5,A,America/New_York
984,NUP,Nunapitchuk Airport,60.905833,-162.439167,12,-9,A,America/Anchorage
415,EDW,Edwards Afb,34.905417,-117.883739,2302,-8,A,America/Los_Angeles
1277,SUN,Friedman Mem,43.504444,-114.296194,5320,-7,A,America/Denver
127,ANB,Anniston Metro,33.588167,-85.858111,612,-6,A,America/Chicago
606,HOP,Campbell Aaf,36.668567,-87.496183,573,-6,A,America/Chicago

## Wybierz 5% losowych wierszy

In [359]:
airports.sample(frac=0.2)

,faa,name,lat,lon,alt,tz,dst,tzone
236,BTV,Burlington Intl,44.471861,-73.153278,335,-5,A,America/New_York
876,MIA,Miami Intl,25.793250,-80.290556,8,-5,A,America/New_York
1444,ZRA,Atlantic City Rail Terminal,39.366500,-74.442000,8,-5,A,America/New_York
344,CYF,Chefornak Airport,60.149167,-164.285556,40,-9,A,America/Anchorage
1385,VSF,Hartness State,43.343333,-72.517222,577,-5,A,America/New_York
1075,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,1135,-7,N,America/Phoenix
1313,TLH,Tallahassee Rgnl,30.396528,-84.350333,81,-5,A,America/New_York
1347,TYS,Mc Ghee Tyson,35.810972,-83.994028,981,-5,A,America/New_York
1352,UDG,Darlington County Jetport,34.449385,-79.890061,192,-5,A,America/New_York
166,AVX,Avalon,33.405000,-118.415833,1602,-8,A,America/Los_Angeles
246,BXS,Borrego Valley Airport,33.259028,-116.320972,520,-8,A,America/Los_Angeles
222,BOI,Boise Air Terminal,43.564361,-116.222861,2871,-7,A,America/Denver
551,GPT,Gulfport-Biloxi,30.407278,-89.070111,28,-6,A,America/Chicago
1198,SCE,University Park Airport,40.849278,-77.848694,1239,-5,A,America/New_York
316,COF,Patrick Afb,28.234922,-80.610125,8,-5,A,America/New_York
272,CDW,Caldwell Essex County Airport,40.875222,-74.281361,172,-5,A,America/New_York
623,HUF,Terre Haute Intl Hulman Fld,39.451464,-87.307561,589,-5,A,America/New_York
560,GSB,Seymour Johnson Afb,35.339383,-77.960589,110,-5,A,America/New_York
606,HOP,Campbell Aaf,36.668567,-87.496183,573,-6,A,America/Chicago
112,AKB,Atka Airport,52.220278,-174.206389,56,-9,A,America/Anchorage
439,ENA,Kenai Muni,60.573111,-151.245000,99,-9,A,America/Anchorage
899,MMU,Morristown Municipal Airport,40.799350,-74.414875,187,-5,A,America/New_York
1383,VPS,Eglin Afb,30.483250,-86.525400,87,-6,A,America/Chicago
1055,PBV,St George,56.578344,-169.661611,125,-9,A,America/Anchorage
1081,PIP,Pilot Point Airport,57.585393,-157.571944,57,-9,A,America/Anchorage
806,LNY,Lanai,20.785611,-156.951419,1308,-10,N,Pacific/Honolulu
1066,PGA,Page Municipal Airport,36.926100,-111.448300,4316,-7,A,America/Phoenix
619,HSV,Huntsville International Airport-Carl T Jones ...,34.637194,-86.775056,629,-6,A,America/Chicago
732,KMY,Moser Bay Seaplane Base,57.025556,-154.145833,0,-9,A,America/Anchorage
219,BMT,Beaumont Municipal,30.070204,-94.215097,32,-6,A,America/Chicago
...,...,...,...,...,...,...,...,...
530,GED,Sussex Co,38.689194,-75.358889,50,-5,A,America/New_York
972,NNL,Nondalton Airport,59.966944,-154.851667,262,-9,A,America/Anchorage
653,IKR,Kirtland Air Force Base,35.040222,-106.609194,5355,-7,A,America/Denver
964,NIP,Jacksonville Nas,30.235834,-81.680556,22,-5,A,America/New_York
948,N53,Stroudsburg-Pocono Airport,41.035872,-75.160679,480,-5,A,America/New_York
547,GNT,Grants Milan Muni,35.167286,-107.901989,6537,-7,A,America/Denver
356,DBQ,Dubuque Rgnl,42.402000,-90.709472,1076,-6,A,America/Chicago
1366,VAD,Moody Afb,30.967833,-83.193000,233,-5,A,America/New_York
1342,TWD,Jefferson County Intl,48.031400,-122.483800,108,-8,A,America/Los_Angeles
1453,ZUN,Black Rock,35.083228,-108.791778,6454,-7,A,America/Denver
1261,SPZ,Silver Springs Airport,39.403028,-119.251194,4269,-8,A,America/Los_Angeles
1420,WYS,Yellowstone Airport,44.688333,-111.117500,6644,-7,A,America/Denver
598,HMN,Holloman Afb,32.852519,-106.106525,4093,-7,A,America/Denver
1429,XFL,Flagler County Airport,29.282100,-81.121200,33,-5,A,America/New_York
394,DUT,Unalaska,53.900139,-166.543500,22,-9,A,America/Anchorage
1177,RWL,Rawlins Municipal Airport-Harvey Field,41.805597,-107.199940,6813,-7,A,America/Denver
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York
1109,PSX,Palacios Muni,28.727508,-96.250958,14,-6,A,America/Chicago
1411,WSJ,San Juan - Uganik Seaplane Base,57.730278,-153.320556,0,-9,A,America/Anchorage
225,BPT,Southeast Texas Rgnl,29.950833,-94.020694,15,-6,A,America/Chicago
1108,PSP,Palm Springs Intl,33.829667,-116.506694,477,-8,A,America/Los_Angeles
211,BLD,Boulder City Municipal Airport,35.565100,-114.514000,2201,-7,U,America/Phoenix
543,GLD,Renner Fld,39.370621,-101.698992,3656,-7,A,America/Denver
1258,SPI,Abraham Lincoln Capital,39.844100,-89.677889,597,-6,A,America/Chicago
406,E91,Chinle Municipal Airport,36.110881,-109.575422,5547,-7,N,America/Denver
277,CEW,Bob Sikes,30.778833,-86.522111,213,-6,A,America/Chicago
118,ALB,Albany Intl,42.748267,-73.801692,285,-5,A,America/New_York
920,MSN,Dane Co Rgnl Truax Fld,43.139858,-89.337514,887,-6,A,America/Chicago
1205,SDP,Sand Point Airport,55.315000,-160.523000,21,-9,A,America/Anchorage
1374,VEE,Venetie Airport,67.008611,-146.366389,574,-9,A,America/Anchorage

## Wybierz pierwszych 100 wierszy

In [364]:
airports.head(100)

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York
15,1B9,Mansfield Municipal,42.000133,-71.196771,122,-5,A,America/New_York
16,1C9,Frazier Lake Airpark,54.013333,-124.768333,152,-8,A,America/Vancouver
17,1CS,Clow International Airport,41.695974,-88.129231,670,-6,U,America/Chicago
18,1G3,Kent State Airport,41.151389,-81.415111,1134,-5,A,America/New_York
19,1G4,Grand Canyon West Airport,35.899904,-113.815674,4813,-7,A,America/Phoenix
20,1H2,Effingham Memorial Airport,39.070000,-88.534000,585,-6,A,America/Chicago
21,1OH,Fortman Airport,40.555325,-84.386619,885,-5,U,America/New_York
22,1RL,Point Roberts Airpark,48.979722,-123.078889,10,-8,A,America/Los_Angeles
23,23M,Clarke CO,32.051700,-88.443400,320,-6,A,America/Chicago
24,24C,Lowell City Airport,42.953920,-85.343906,681,-5,A,America/New_York
25,24J,Suwannee County Airport,30.300125,-83.024694,104,-5,A,America/New_York
26,25D,Forest Lake Airport,45.247746,-92.994385,925,-6,A,America/Chicago
27,29D,Grove City Airport,41.146028,-80.167750,1371,-5,A,America/New_York
28,2A0,Mark Anton Airport,35.486250,-84.931083,718,-5,A,America/New_York
29,2B2,Plum Island Airport,42.795361,-70.839444,11,-5,A,America/New_York
...,...,...,...,...,...,...,...,...
70,70N,Spring Hill Airport,41.347357,-75.415897,1729,-5,A,America/New_York
71,7A4,Foster Field,42.466444,-90.169389,990,-6,A,America/Chicago
72,7D9,Germack Airport,41.777832,-80.903980,820,-5,A,America/New_York
73,7N7,Spitfire Aerodrome,39.735563,-75.397721,40,-5,A,America/New_York
74,8M8,Garland Airport,44.806528,-84.276194,1218,-5,A,America/New_York
75,93C,Richland Airport,43.283358,-90.298282,742,-6,A,America/Chicago
76,99N,Bamberg County Airport,33.304528,-81.108417,231,-5,A,America/New_York
77,9A1,Covington Municipal Airport,33.632308,-83.847447,809,-5,A,America/New_York
78,9A5,Barwick Lafayette Airport,34.688479,-85.290332,777,-5,A,America/New_York
79,9G1,Rock Airport,40.603546,-79.826119,1063,-5,A,America/New_York
80,A39,Phoenix Regional Airport,32.991699,-111.920998,1300,-7,A,America/Phoenix
81,A50,Colorado Springs East,38.870000,-104.410000,6145,-7,A,America/Denver
82,AAF,Apalachicola Regional Airport,29.727607,-85.027442,20,-5,A,America/New_York
83,AAP,Andrau Airport,29.430000,-95.350000,80,-6,A,America/Chicago
84,ABE,Lehigh Valley Intl,40.652083,-75.440806,393,-5,A,America/New_York
85,ABI,Abilene Rgnl,32.411319,-99.681897,1791,-6,A,America/Chicago
86,ABL,Ambler Airport,67.106389,-157.857500,334,-9,A,America/Anchorage
87,ABQ,Albuquerque International Sunport,35.040222,-106.609194,5355,-7,A,America/Denver
88,ABR,Aberdeen Regional Airport,45.449100,-98.421800,1302,-6,A,America/Chicago
89,ABY,Southwest Georgia Regional Airport,31.535500,-84.194500,197,-5,A,America/New_York
90,ACJ,Jimmy Carter Regional,32.066500,-84.113300,468,-5,A,America/New_York
91,ACK,Nantucket Mem,41.253053,-70.060181,48,-5,A,America/New_York
92,ACT,Waco Rgnl,31.611289,-97.230519,516,-6,A,America/Chicago
93,ACV,Arcata,40.978111,-124.108611,221,-8,A,America/Los_Angeles
94,ACY,Atlantic City Intl,39.457583,-74.577167,75,-5,A,America/New_York
95,ADK,Adak Airport,51.878000,-176.646000,18,-9,A,America/Anchorage
96,ADM,Ardmore Muni,34.300833,-97.008889,762,-6,A,America/Chicago
97,ADQ,Kodiak,57.749967,-152.493856,78,-9,A,America/Anchorage
98,ADS,Addison,32.968559,-96.836448,644,-6,A,America/Chicago
99,ADW,Andrews Afb,38.810806,-76.867028,280,-5,A,America/New_York

In [363]:
## Wybierz ostatnich 100 wierszy

In [365]:
airports.tail(100)

,faa,name,lat,lon,alt,tz,dst,tzone
1358,UPP,Upolu,20.265256,-155.859989,96,-10,A,Pacific/Honolulu
1359,UST,St. Augustine Airport,29.959167,-81.339722,10,-5,A,America/New_York
1360,UT3,Hite Airport,37.891655,-110.384029,3840,-7,A,America/Denver
1361,UTM,Tunica Municipal Airport,34.681000,-90.346700,194,-6,A,America/Chicago
1362,UTO,Indian Mountain Lrrs,65.992794,-153.704289,1220,-9,A,America/Anchorage
1363,UUK,Ugnu-Kuparuk Airport,70.330833,-149.597500,67,-9,A,America/Anchorage
1364,UUU,Newport State,41.533056,-71.282222,172,-5,A,America/New_York
1365,UVA,Garner Field,29.215429,-99.748962,942,-6,A,America/Chicago
1366,VAD,Moody Afb,30.967833,-83.193000,233,-5,A,America/New_York
1367,VAK,Chevak Airport,61.533800,-165.584000,75,-9,A,America/Anchorage
1368,VAY,South Jersey Regional Airport,39.942889,-74.845750,53,-5,A,America/New_York
1369,VBG,Vandenberg Afb,34.737333,-120.584306,369,-8,A,America/Los_Angeles
1370,VCT,Victoria Regional Airport,28.852600,-96.918500,115,-6,A,America/Chicago
1371,VCV,Southern California Logistics,34.597453,-117.382997,2885,-8,A,America/Los_Angeles
1372,VDF,Tampa Executive Airport,28.013977,-82.345278,22,-5,A,America/New_York
1373,VDZ,Valdez Pioneer Fld,61.133949,-146.248342,118,-9,A,America/Anchorage
1374,VEE,Venetie Airport,67.008611,-146.366389,574,-9,A,America/Anchorage
1375,VEL,Vernal Regional Airport,40.440833,-109.510000,5278,-7,A,America/Denver
1376,VGT,North Las Vegas Airport,36.210694,-115.194444,2205,-8,U,America/Los_Angeles
1377,VIS,Visalia Municipal Airport,36.318611,-119.392778,295,-8,A,America/Los_Angeles
1378,VLD,Valdosta Regional Airport,30.782500,-83.276700,203,-5,A,America/New_York
1379,VNW,Van Wert County Airport,40.863830,-84.606358,787,-5,A,America/New_York
1380,VNY,Van Nuys,34.209811,-118.489972,802,-8,A,America/Los_Angeles
1381,VOK,Volk Fld,43.938956,-90.253433,912,-6,A,America/Chicago
1382,VPC,Cartersville Airport,34.123147,-84.848707,759,-5,A,America/New_York
1383,VPS,Eglin Afb,30.483250,-86.525400,87,-6,A,America/Chicago
1384,VRB,Vero Beach Muni,27.655556,-80.417944,24,-5,A,America/New_York
1385,VSF,Hartness State,43.343333,-72.517222,577,-5,A,America/New_York
1386,VYS,Illinois Valley Regional,41.351944,-89.153056,654,-6,A,America/Chicago
1387,W04,Ocean Shores Municipal,46.599500,-124.085400,15,-8,A,America/Los_Angeles
...,...,...,...,...,...,...,...,...
1428,X59,Valkaria Municipal,27.960861,-80.558333,26,-5,A,America/New_York
1429,XFL,Flagler County Airport,29.282100,-81.121200,33,-5,A,America/New_York
1430,XNA,NW Arkansas Regional,36.281869,-94.306811,1287,-6,A,America/Chicago
1431,XZK,Amherst Amtrak Station AMM,42.375000,-72.511389,258,-5,A,America/New_York
1432,Y51,Municipal Airport,43.579360,-90.896474,1292,-6,A,America/Chicago
1433,Y72,Bloyer Field,43.976222,-90.480611,966,-6,A,America/Chicago
1434,YAK,Yakutat,59.301200,-139.393700,33,-9,A,\N
1435,YIP,Willow Run,42.237928,-83.530408,716,-5,A,America/New_York
1436,YKM,Yakima Air Terminal McAllister Field,46.568200,-120.544000,1095,-8,A,America/Los_Angeles
1437,YKN,Chan Gurney,42.871100,-97.396900,1200,-6,A,America/Chicago
1438,YNG,Youngstown Warren Rgnl,41.260736,-80.679097,1196,-5,A,America/New_York
1439,YUM,Yuma Mcas Yuma Intl,32.656578,-114.605980,216,-7,N,America/Phoenix
1440,Z84,Clear,64.301203,-149.120144,552,-9,A,America/Anchorage
1441,ZBP,Penn Station,39.307222,-76.615556,66,-5,A,America/New_York
1442,ZFV,Philadelphia 30th St Station,39.955700,-75.182000,0,-5,A,America/New_York
1443,ZPH,Municipal Airport,28.228056,-82.155833,90,-5,A,America/New_York
1444,ZRA,Atlantic City Rail Terminal,39.366500,-74.442000,8,-5,A,America/New_York
1445,ZRD,Train Station,37.534300,-77.429450,26,-5,A,America/New_York
1446,ZRP,Newark Penn Station,40.734722,-74.164167,0,-5,A,America/New_York
1447,ZRT,Hartford Union Station,41.768880,-72.681500,0,-5,A,America/New_York
1448,ZRZ,New Carrollton Rail Station,38.948000,-76.871900,39,-5,A,America/New_York
1449,ZSF,Springfield Amtrak Station,42.106000,-72.593054,65,-5,A,America/New_York
1450,ZSY,Scottsdale Airport,33.622889,-111.910528,1519,-7,A,America/Phoenix
1451,ZTF,Stamford Amtrak Station,41.046937,-73.541493,0,-5,A,America/New_York
1452,ZTY,Boston Back Bay Station,42.347800,-71.075000,20,-5,A,America/New_York
1453,ZUN,Black Rock,35.083228,-108.791778,6454,-7,A,America/Denver
1454,ZVE,New Haven Rail Station,41.298669,-72.925992,7,-5,A,America/New_York
1455,ZWI,Wilmington Amtrak Station,39.736667,-75.551667,0,-5,A,America/New_York
1456,ZWU,Washington Union Station,38.897460,-77.006430,76,-5,A,America/New_York
1457,ZYP,Penn Station,40.750500,-73.993500,35,-5,A,America/New_York

## Teoriomnogościowe

In [368]:
A = airports[0:10]
B = airports[5:15]

In [369]:
A.shape

(10, 8)

In [370]:
B.shape

(10, 8)

## SELECT * FROM A UNION ALL SELECT * FROM B

In [377]:
pd.concat([A, B])

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York

## SELECT * FROM A UNION SELECT * FROM B

In [390]:
result = pd.concat([A, B]).drop_duplicates()
result

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York

## SELECT * FROM A INTERSECT SELECT * FROM B

In [393]:
result = pd.concat([A, B])
result[result.duplicated()]

,faa,name,lat,lon,alt,tz,dst,tzone
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles

## SELECT * FROM A EXCEPT SELECT * FROM B

In [399]:
A[~A.isin(B)].dropna()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044.0,-5.0,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264.0,-6.0,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801.0,-6.0,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523.0,-5.0,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11.0,-5.0,A,America/New_York

## SELECT * FROM B EXCEPT SELECT * FROM A

In [400]:
B[~B.isin(A)].dropna()

,faa,name,lat,lon,alt,tz,dst,tzone
10,0W3,Harford County Airport,39.566838,-76.202403,409.0,-5.0,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875.0,-6.0,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003.0,-5.0,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951.0,-5.0,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789.0,-5.0,A,America/New_York

## Złącz flights z planes

In [404]:
flights.columns

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')

In [402]:
planes.columns

Index(['tailnum', 'year', 'type', 'manufacturer', 'model', 'engines', 'seats',
       'speed', 'engine'],
      dtype='object')

In [405]:
pd.merge(left=flights, right=planes, how='inner', left_on='tailnum', right_on='tailnum')

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,minute,time_hour,year_y,type,manufacturer,model,engines,seats,speed,engine
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,15,2013-01-01 05:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
1,2013,1,8,1435.0,1440,-5.0,1717.0,1746,-29.0,UA,...,40,2013-01-08 14:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
2,2013,1,9,717.0,700,17.0,812.0,815,-3.0,UA,...,0,2013-01-09 07:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
3,2013,1,9,1143.0,1144,-1.0,1425.0,1445,-20.0,UA,...,44,2013-01-09 11:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
4,2013,1,13,835.0,824,11.0,1030.0,951,39.0,UA,...,24,2013-01-13 08:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
5,2013,1,16,1829.0,1730,59.0,2117.0,2023,54.0,UA,...,30,2013-01-16 17:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
6,2013,1,22,1902.0,1808,54.0,2214.0,2106,68.0,UA,...,8,2013-01-22 18:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
7,2013,1,23,1050.0,1056,-6.0,1143.0,1208,-25.0,UA,...,56,2013-01-23 10:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
8,2013,1,23,1533.0,1529,4.0,1641.0,1645,-4.0,UA,...,29,2013-01-23 15:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
9,2013,1,25,724.0,720,4.0,1000.0,1023,-23.0,UA,...,20,2013-01-25 07:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
10,2013,1,25,1525.0,1529,-4.0,1818.0,1837,-19.0,UA,...,29,2013-01-25 15:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
11,2013,1,26,1235.0,1235,0.0,1558.0,1609,-11.0,UA,...,35,2013-01-26 12:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
12,2013,1,28,1832.0,1830,2.0,2147.0,2148,-1.0,UA,...,30,2013-01-28 18:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
13,2013,1,29,1438.0,1440,-2.0,1724.0,1752,-28.0,UA,...,40,2013-01-29 14:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
14,2013,1,31,1736.0,1727,9.0,2057.0,2049,8.0,UA,...,27,2013-01-31 17:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
15,2013,10,1,1115.0,1115,0.0,1311.0,1334,-23.0,UA,...,15,2013-10-01 11:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
16,2013,10,6,1150.0,1155,-5.0,1439.0,1507,-28.0,UA,...,55,2013-10-06 11:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
17,2013,10,9,954.0,1000,-6.0,1326.0,1321,5.0,UA,...,0,2013-10-09 10:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
18,2013,10,10,1935.0,1803,92.0,2240.0,2117,83.0,UA,...,3,2013-10-10 18:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
19,2013,10,16,642.0,648,-6.0,805.0,817,-12.0,UA,...,48,2013-10-16 06:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
20,2013,10,17,1024.0,1030,-6.0,1320.0,1326,-6.0,UA,...,30,2013-10-17 10:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
21,2013,10,24,834.0,834,0.0,1157.0,1156,1.0,UA,...,34,2013-10-24 08:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
22,2013,10,29,1051.0,1100,-9.0,1430.0,1408,22.0,UA,...,0,2013-10-29 11:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
23,2013,12,22,937.0,900,37.0,1247.0,1248,-1.0,UA,...,0,2013-12-22 09:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
24,2013,12,26,922.0,909,13.0,1044.0,1045,-1.0,UA,...,9,2013-12-26 09:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
25,2013,12,28,1903.0,1847,16.0,2126.0,2121,5.0,UA,...,47,2013-12-28 18:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
26,2013,2,4,1443.0,1447,-4.0,1541.0,1557,-16.0,UA,...,47,2013-02-04 14:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
27,2013,2,7,1115.0,1114,1.0,1344.0,1345,-1.0,UA,...,14,2013-02-07 11:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
28,2013,2,11,1550.0,1555,-5.0,1809.0,1846,-37.0,UA,...,55,2013-02-11 15:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
29,2013,2,14,1057.0,1059,-2.0,1353.0,1441,-48.0,UA,...,59,2013-02-14 10:00:00,1999.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284140,2013,9,27,1838.0,1840,-2.0,2102.0,2116,-14.0,DL,...,40,2013-09-27 18:00:00,1990.0,Fixed wing multi engine,BOEING,767-3P6,2,290,NaN,Turbo-fan
284141,2013,8,28,2039.0,1805,154.0,2213.0,1953,140.0,OO,...,5,2013-08-28 18:00:00,2009.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284142,2013,8,29,1631.0,1620,11.0,1842.0,1902,-20.0,DL,...,20,2013-08-29 16:00:00,2002.0,Fixed wing multi engine,BOEING,767-432ER,2,300,NaN,Turbo-jet
284143,2013,8,29,1832.0,1805,27.0,2039.0,1953,46.0,OO,...,5,2013-08-29 18:00:00,2010.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284144,2013,8,30,1930.0,1805,85.0,2102.0,1953,69.0,OO,...,5,2013-08-30 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284145,2013,8,31,1511.0,1400,71.0,1730.0,1630,60.0,DL,...,0,2013-08-31 14:00:00,1997.0,Fixed wing multi engine,MCDONNELL DOUGLAS,MD-90-30,2,142,NaN,Turbo-jet
284146,2013,9,2,NaN,1805,NaN,NaN,1953,NaN,OO,...,5,2013-09-02 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284147,2013,9,3,1759.0,1805,-6.0,1959.0,1953,6.0,OO,...,5,2013-09-03 18:00:00,2010.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284148,2013,9,4,1803.0,1805,-2.0,1941.0,1953,-12.0,OO,...,5,2013-09-04 18:00:00,2009.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284149,2013,9,9,1757.0,1805,-8.0,1951.0,1953,-2.0,OO,...,5,2013-09-09 18:00:00,2009.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284150,2013,9,5,1855.0,1855,0.0,2155.0,2131,24.0,DL,...,55,2013-09-05 18:00:00,1998.0,Fixed wing multi engine,BOEING,767-332,2,330,NaN,Turbo-fan
284151,2013,9,6,1803.0,1805,-2.0,1945.0,1953,-8.0,OO,...,5,2013-09-06 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284152,2013,9,8,1754.0,1805,-11.0,1946.0,1953,-7.0,OO,...,5,2013-09-08 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284153,2013,9,10,1759.0,1805,-6.0,1945.0,1953,-8.0,OO,...,5,2013-09-10 18:00:00,2004.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284154,2013,9,11,NaN,1805,NaN,NaN,1953,NaN,OO,...,5,2013-09-11 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284155,2013,9,13,1656.0,1545,71.0,1838.0,1723,75.0,EV,...,45,2013-09-13 15:00:00,1997.0,Fixed wing multi engine,CANADAIR,CL-600-2B19,2,55,NaN,Turbo-fan
284156,2013,9,13,1845.0,1805,40.0,2041.0,1953,48.0,OO,...,5,2013-09-13 18:00:00,2004.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284157,2013,9,14,712.0,720,-8.0,932.0,1025,-53.0,AS,...,20,2013-09-14 07:00:00,2006.0,Fixed wing multi engine,BOEING,737-890,2,149,NaN,Turbo-fan
284158,2013,9,15,1756.0,1805,-9.0,1929.0,1953,-24.0,OO,...,5,2013-09-15 18:00:00,2006.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284159,2013,9,16,1744.0,1310,274.0,1944.0,1508,276.0,EV,...,10,2013-09-16 13:00:00,2003.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2B19,2,55,NaN,Turbo-fan
284160,2013,9,16,1752.0,1805,-13.0,1939.0,1953,-14.0,OO,...,5,2013-09-16 18:00:00,2004.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284161,2013,9,17,1755.0,1805,-10.0,1937.0,1953,-16.0,OO,...,5,2013-09-17 18:00:00,2010.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284162,2013,9,18,1237.0,1240,-3.0,1515.0,1525,-10.0,WN,...,40,2013-09-18 12:00:00,1996.0,Fixed wing multi engine,BOEING,737-3H4,2,149,NaN,Turbo-fan
284163,2013,9,18,1754.0,1805,-11.0,1927.0,1953,-26.0,OO,...,5,2013-09-18 18:00:00,2004.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284164,2013,9,19,1759.0,1805,-6.0,1946.0,1953,-7.0,OO,...,5,2013-09-19 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284165,2013,9,20,1758.0,1805,-7.0,1929.0,1953,-24.0,OO,...,5,2013-09-20 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284166,2013,9,22,1759.0,1805,-6.0,1945.0,1953,-8.0,OO,...,5,2013-09-22 18:00:00,2005.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284167,2013,9,23,1759.0,1805,-6.0,1935.0,1953,-18.0,OO,...,5,2013-09-23 18:00:00,2006.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284168,2013,9,24,1751.0,1805,-14.0,1937.0,1953,-16.0,OO,...,5,2013-09-24 18:00:00,2009.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2C10,2,80,NaN,Turbo-fan
284169,2013,9,28,712.0,720,-8.0,955.0,1025,-30.0,AS,...,20,2013-09-28 07:00:00,2006.0,Fixed wing multi engine,BOEING,737-890,2,149,NaN,Turbo-fan